project_id = "zefputjjkytoacjdmijy"

[functions.generate-timetable]
verify_jwt = false

[functions.share-timetable]
verify_jwt = false

[functions.download-timetable]
verify_jwt = false

[functions.import-data]
verify_jwt = false

[functions.assign-lab-schedules]
verify_jwt = false