// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zefputjjkytoacjdmijy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZnB1dGpqa3l0b2FjamRtaWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDY4NDQsImV4cCI6MjA2ODQ4Mjg0NH0.MQpqCAxzfakJuEH_VACgwyYGurLF--LVT9B9hep1QhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});